---
require:
- rubocop/require_tools
- rubocop-performance
AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Include:
  - "**/*.rb"
  - "**/*file"
  - "**/*.gemspec"
  - "*/lib/assets/*Template"
  - "*/lib/assets/*TemplateAndroid"
  Exclude:
  - "**/lib/assets/custom_action_template.rb"
  - "./vendor/**/*"
  - "**/lib/assets/DefaultFastfileTemplate"
  - "**/lib/assets/MatchfileTemplate"
  - "**/spec/fixtures/broken_files/broken_file.rb"
  - "**/*.provisionprofile"
Lint:
  Enabled: false
Style:
  Enabled: false
Layout:
  Enabled: false
Performance/RegexpMatch:
  Enabled: false
Performance/StringReplacement:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Require/MissingRequireStatement:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/ClassLength:
  Max: 320
Metrics/ParameterLists:
  Max: 17
Naming/PredicateName:
  Enabled: false
Naming/FileName:
  Exclude:
  - "**/Dangerfile"
  - "**/Brewfile"
  - "**/Gemfile"
  - "**/Podfile"
  - "**/Rakefile"
  - "**/Fastfile"
  - "**/Deliverfile"
  - "**/Snapfile"
  - "**/Pluginfile"
  - "**/*.gemspec"
