lane :test do
	sdkmanager_find(api: 'android-31', platform: 'google_apis')

	results = lane_context[SharedValues::SDKMANAGER_FIND_RESULTS]
	first = results.first

	UI.message first

# 	sdkmanager_install(package_path: first.path)
#
# 	avdmanager_create(
# 		name: 'TEST',
# 		package: 'system-images;android-31;google_apis;x86_64',
# 		device: 'pixel_5',
# 		size: '4096M',
# 	)

# 	avdmanager_create(
# 		name: 'TEST',
# 		package: 'system-images;android-32;google_apis;arm64-v8a',
# 		device: 'pixel_5',
# 		size: '4096M',
# 	)
#
# 	avdmanager_delete()
#
# 	avdmanager_execute(
# 		name: 'TEST',
# 		package: 'system-images;android-32;google_apis;arm64-v8a',
# 		device: 'pixel_5',
# 		size: '4096M',
# 		block: ->(name) {
# 			UI.message "Executing stuff with #{name} running..."
# 		}
# 	)
end
